import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: "Helvetica",
    backgroundColor: "#FFFFFF",
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#0E1116",
    paddingBottom: 15,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoSection: {
    flexDirection: "column",
  },
  university: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0E1116",
  },
  career: {
    fontSize: 10,
    color: "#4A515E",
    marginTop: 2,
    letterSpacing: 1,
  },
  titleSection: {
    textAlign: "right",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1D3FD9",
  },
  subtitle: {
    fontSize: 8,
    color: "#4A515E",
    marginTop: 4,
    fontFamily: "Helvetica-Oblique",
  },
  metaGrid: {
    flexDirection: "row",
    backgroundColor: "#F9F7F2",
    borderWidth: 1,
    borderColor: "#D8D1BD",
    borderRadius: 6,
    padding: 10,
    marginBottom: 20,
  },
  metaItem: {
    flex: 1,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: "#D8D1BD",
  },
  metaItemLast: {
    flex: 1,
    paddingHorizontal: 10,
  },
  metaLabel: {
    fontSize: 7,
    color: "#4A515E",
    textTransform: "uppercase",
    fontWeight: "bold",
  },
  metaValue: {
    fontSize: 10,
    color: "#0E1116",
    marginTop: 2,
    fontWeight: "bold",
  },
  table: {
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#D8D1BD",
    borderRadius: 6,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#E5DFCC",
    overflow: "hidden",
  },
  tableRowHeader: {
    flexDirection: "row",
    backgroundColor: "#0E1116",
    minHeight: 22,
    alignItems: "center",
  },
  tableColHeaderHour: {
    width: "70px",
    textAlign: "center",
    justifyContent: "center",
  },
  tableColHeaderDay: {
    flex: 1,
    textAlign: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "#4A515E",
  },
  tableCellHeader: {
    color: "#F5F1E8",
    fontSize: 8,
    fontWeight: "bold",
  },
  tableColHour: {
    width: "70px",
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#E5DFCC",
    backgroundColor: "#F9F7F2",
  },
  tableCellHour: {
    fontSize: 8,
    fontFamily: "Courier",
    color: "#4A515E",
  },
  tableColDay: {
    flex: 1,
    padding: 0,
    justifyContent: "flex-start",
    borderRightWidth: 1,
    borderRightColor: "#E5DFCC",
    position: "relative",
    overflow: "hidden",
  },
  tableColDayLast: {
    flex: 1,
    padding: 0,
    justifyContent: "flex-start",
    position: "relative",
    overflow: "hidden",
  },
  sessionBlock: {
    borderRadius: 3,
    padding: 4,
    borderWidth: 1,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  sessionMateria: {
    fontSize: 7,
    fontWeight: "bold",
  },
  sessionDocente: {
    fontSize: 6,
    color: "#4A515E",
    marginTop: 1,
  },
  sessionFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 2,
    marginTop: 2,
  },
  sessionGroup: {
    fontSize: 6,
    fontWeight: "bold",
  },
  sessionAula: {
    fontSize: 5,
    backgroundColor: "rgba(0,0,0,0.05)",
    paddingHorizontal: 2,
    borderRadius: 2,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    borderTopWidth: 1,
    borderTopColor: "#E5DFCC",
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: "#8A8F99",
  },
});
